export const RECEIVE_RECIPE = 'RECEIVE_RECIPE';
export const REQUEST_RECIPE = 'REQUEST_RECIPE';
export const CHANGE_RECIPE = 'CHANGE_RECIPE';
export const REDIRECT_HOME = 'REDIRECT_HOME';
export const ASSIGN_ID = 'ASSIGN_ID';
